apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-db
  labels:
    app: customer-service
spec:
  selector:
    matchLabels:
      app: customer-service
      tier: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
        tier: postgresql
    spec:
      containers:
      - image: postgres:latest
        name: postgresql
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: customer-service
        - name: POSTGRES_PASSWORD
          value: guest
        - name: POSTGRES_USER
          value: guest
