apiVersion: v1
kind: Service
metadata:
  name: customer-service-db
  labels:
    app: customer-service
spec:
  ports:
  - port: 5432
  selector:
    app: customer-service
    tier: postgresql
  clusterIP: None
